apiVersion: v1
entries:
  test:
  - apiVersion: v2
    created: "2024-03-07T11:53:03.487024175Z"
    description: A Helm chart for Kubernetes
    digest: 8f3de33b2fb3f1663ff1dbd0ca117d36fa8a04446563ee7d4ad6781f915feef7
    name: test
    type: application
    urls:
    - test-1.23.0.tgz
    version: 1.23.0
  - apiVersion: v2
    created: "2024-03-07T11:53:03.487411711Z"
    description: A Helm chart for Kubernetes
    digest: 513bab546691d7d62f813ea9b0a4b608357da494380ce6aceabfb50ca640efdf
    name: test
    type: application
    urls:
    - test-1.23.7.tgz
    version: 1.23.7
  - apiVersion: v2
    created: "2024-03-07T11:53:03.487758339Z"
    description: A Helm chart for Kubernetes
    digest: 4d024e0ba07de745ee770cc88a4144d2fb2baa39e8290decc338ca312e2dc26b
    name: test
    type: application
    urls:
    - test-1.23.8.tgz
    version: 1.23.8
  - apiVersion: v2
    created: "2024-03-07T11:53:03.488098105Z"
    description: A Helm chart for Kubernetes
    digest: d6d1cac46e41ac549b6d42e40d3da2a2ccf35f0d875685ec35dc3f69d49962da
    name: test
    type: application
    urls:
    - test-1.23.9.tgz
    version: 1.23.9
  - apiVersion: v2
    created: "2024-03-07T11:53:03.488445004Z"
    description: A Helm chart for Kubernetes
    digest: 4ec6dc0469bbc8de82145f1c78036acc1c9a0d3545b73ae93428250afd230a33
    name: test
    type: application
    urls:
    - test-1.3.6.tgz
    version: 1.3.6
generated: "2024-03-07T11:53:03.486321682Z"
